data:
  type: sentiment
  human: data/human/sentiment-analysis/lalor/sa_lalor_human.csv
  machine: data/machine/sentiment-analysis/lalor/machine_1/mc_dropout/trues.csv

correlation:
  type: human+machine
  method: spearman
  columns:
    human:
      - average_accuracy
      - flesch_score_textstat
      - mean_grade_level_textstat
    machine:
      - pred_confidence
      - gold_confidence
      - uncertainty
  results:
    dir: results/correlation/sentiment-analysis/lalor/human+machine_1/
    heatmap:
      name: true_heatmap.png
      title: human+machine_1 correlations of true preds
    excel:
      name:  true_correlations.xlsx