data:
  type: language-inference
  human: results/language-inference/lalor/files/human.csv
  machine: results/language-inference/lalor/files/tfidf.csv

correlation:
  type: human+machine
  method: spearman
  columns:
    human:
      - agg_human_conf
    machine:
      - confidence
  results:
    dir: results/correlation/language-inference/lalor/human+machine_1/
    heatmap:
      name:  all_heatmap.png
      title: human+TFIDF correlations
    excel:
      name:  all_correlations.xlsx