data:
  type: sentiment
  human: data/human/sentiment-analysis/zuco/all.csv
  machine: data/machine/language-inference/lalor/machine_1/snli_retrained.csv

correlation:
  type: machine
  method: spearman
  columns:
    human:
      - mean_of_fixations
      - max_of_fixations
      - mean_of_trts
      - mean_of_omissionRates
    machine:
      - average_accuracy
      - flesch_score_textstat
      - softmax_entropy
  results:
    dir: results/correlation/language-inference/lalor/human+machine_1/
    heatmap:
      name:  all_heatmap.png
      title: human+machine_1 correlations
    excel:
      name:  all_correlations.xlsx