data:
  type: language-inference
  human: data/human/SNLI-lalor/snli_human_4gs.csv
  machine: results/SNLI-lalor/v2_tilek_merged_results_all.csv

correlation:
  type: human+machine
  method: spearman
  columns:
    human:
      - item_difficulty
    machine:
      #- machine_0_confidence
      - machine_1_confidence
      - machine_2_confidence
      - machine_3_confidence
      - machine_4_confidence
      - agg_human_confidence
  results:
    dir: results/SNLI-lalor/correlation/
    heatmap:
      name:  heatmap.png
      title: mix-of-humans vs. machines
    excel:
      name:  correlations.xlsx