data:
  type: language-inference
  human: user-study/results/results_with_diff_scores.csv
  machine: results/language-inference/lalor/files/lstm.csv

correlation:
  type: human+machine
  method: spearman
  columns:
    human:
      - diff_score
    machine:
      - Entropy
  results:
    dir: results/correlation/language-inference/lalor/human+machine_2/
    heatmap:
      name:  all_heatmap.png
      title: human+LSTM correlations
    excel:
      name:  all_correlations.xlsx