data:
  type: language-inference
  human: results/language-inference/lalor/files/human.csv
  machine: user-study/results/results_with_diff_scores.csv

correlation:
  type: human+machine
  method: spearman
  columns:
    human:
      - agg_human_conf
    machine:
      - diff_score
      - avg_userstudy_accuracy
      - avg_userstudy_confidence
      - agg_userstudy_accuracy
      - agg_userstudy_confidence

  results:
    dir: results/correlation/language-inference/lalor/human+machine_userstudy/
    heatmap:
      name:  userstudy-diffscore_userstudy-aggacc.png
      title: user_study difficulty-acc correlations
    excel:
      name:  userstudy-diffscore_userstudy-avgacc.xlsx