data:
  type: sentiment
  human: data/human/sentiment-analysis/all.csv
  machine: data/machine/sentiment-analysis/all.csv

correlation:
  type: human+machine 
  method: spearman
  columns:
    human:
      - mean_of_fixations
      - max_of_fixations
      - mean_of_trts
      - mean_of_omissionRates
      - average_item_accuracy
    machine:
      - BERT_SOFTMAX_ENTROPY  
      - BERT_MC_DROPOUT
  results:
    dir: results/sentiment-analysis/
    heatmap:
      name:  all_heatmap.png
      title: correlations
    excel:
      name:  all_correlations.xlsx