data:
  type: sentiment
  file: data/human/sentiment-analysis/zuco/control.csv
metrics:
  - pred_confidence
  - gold_confidence
  - uncertainty  
model: 
  name: Souvikcmsa/BERT_sentiment_analysis
  id: 1
  calibration: 
    method: mc_dropout
    num_iters: 5
results:
    dir: data/machine/sentiment-analysis/zuco/machine_1/mc_dropout
    file: control.csv